name: PR checks
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build js
        run: yarn build
    
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint js and scss
        run: yarn run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test js
        run: yarn run test
